name: Complete Architect
on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Run a sample
      - run: echo"This Wokflow run successfully."
